# Generated by Django 4.1.2 on 2022-10-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modaforge', '0002_testentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testEntity',
        ),
    ]
