// Generated by https://quicktype.io

export interface Model {
    results: Result[];
}

export interface Result {
    uid:             string;
    tags:            Tag[];
    viewerUrl:       string;
    isProtected:     boolean;
    price:           number;
    categories:      Category[];
    publishedAt:     string;
    likeCount:       number;
    commentCount:    number;
    viewCount:       number;
    vertexCount:     number;
    user:            User;
    isDownloadable:  boolean;
    animationCount:  number;
    name:            string;
    license:         string;
    soundCount:      number;
    isAgeRestricted: boolean;
    uri:             string;
    faceCount:       number;
    createdAt:       string;
    thumbnails:      Thumbnails;
    embedUrl:        string;
    archives:        { [key: string]: Archive };
}

export interface Archive {
    faceCount:            number;
    textureCount:         number;
    size:                 number;
    vertexCount:          number;
    textureMaxResolution: number;
}

export interface Category {
    uri:  string;
    uid:  string;
    name: string;
    slug: string;
}

export interface Tag {
    slug: string;
    uri:  string;
}

export interface Thumbnails {
    images: Image[];
}

export interface Image {
    url:    string;
    width:  number;
    uid?:   string;
    height: number;
    size?:  number;
}

export interface User {
    username:    string;
    profileUrl:  string;
    account:     string;
    displayName: string;
    uid:         string;
    uri:         string;
    avatar:      Avatar[];
}

export interface Avatar {
    images: Image[];
    uid:    string;
    uri:    string;
}
