// Generated by https://quicktype.io

export interface ModelDetail {
    uid:                 string;
    publishedAt:         string;
    likeCount:           number;
    commentCount:        number;
    updatedAt:           string;
    isDownloadable:      boolean;
    isAgeRestricted:     boolean;
    pbrType:             string;
    materialCount:       number;
    name:                string;
    source:              string;
    createdAt:           string;
    embedUrl:            string;
    status:              License;
    tags:                Tag[];
    viewerUrl:           string;
    isProtected:         boolean;
    price:               number;
    textureCount:        number;
    vertexCount:         number;
    user:                User;
    categories:          Category[];
    animationCount:      number;
    viewCount:           number;
    thumbnails:          Thumbnails;
    license:             License;
    editorUrl:           string;
    soundCount:          number;
    uri:                 string;
    faceCount:           number;
    hasCommentsDisabled: boolean;
    downloadCount:       number;
}

export interface Category {
    uri:  string;
    uid:  string;
    name: string;
    slug: string;
}

export interface License {
}

export interface Tag {
    slug: string;
    uri:  string;
}

export interface Thumbnails {
    images: Image[];
}

export interface Image {
    url:    string;
    width:  number;
    uid?:   string;
    height: number;
    size?:  number;
}

export interface User {
    username:    string;
    profileUrl:  string;
    account:     string;
    displayName: string;
    uid:         string;
    uri:         string;
    avatar:      Avatar[];
}

export interface Avatar {
    images: Image[];
    uid:    string;
    uri:    string;
}
